Bugfix/number of chars in title
storytallers2020/StoryTallers2020 pull request #168
Opened 2021-02-10 16:11 UTC by Vitas1968

Реализация прогрессбара во фрагментах где идет загрузка изображений с сервера

2021-02-12 10:17 UTC, KatherineZharkova approved these changes
Внесла немного правок, чисто небольшой рефакторинг)

2021-02-28 08:15 UTC, KatherineZharkova requested changes
needs refactoring

2021-02-28 08:59 UTC, KatherineZharkova approved these changes

2021-03-01 13:16 UTC, closed without merging

2021-03-01 13:17 UTC, Vitas1968 commented
Я сделал более свежие обновления